---
# NOTE: Refer drone Go example http://readme.drone.io/0.5/usage/golang-example/
workspace:
  base: /go
  path: src/github.com/hnakamur/go-test-example

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
